name: "Build"

on:
  push:
    branches:
      - dev
      - hml
      - main

permissions:
  contents: write

jobs:
  create-tag:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/hml' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: dev
            env_name: Dev
            suffix: "dev"
          - branch: hml
            env_name: Hml
            suffix: "hml"
          - branch: main
            env_name: Prd
            suffix: ""
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Ensure full history is fetched

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Determine version
        run: |
          # Determine the base version (X.Y.Z) from the package.json
          BASE_VERSION=$(node -p "require('./package.json').version")

          # Get the build number
          BUILD_NUMBER=$(git rev-list --count HEAD)

          # Determine the suffix based on the branch
          if [ "${{ matrix.env_name }}" == "Prd" ]; then
            VERSION="$BASE_VERSION"
          else
            VERSION="$BASE_VERSION-${{ matrix.suffix }}.$BUILD_NUMBER"
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Print version
        run: echo "Creating tag for version ${{ env.VERSION }}"

      - name: Create Release Tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag -a "${{ env.VERSION }}" -m "Release ${{ env.VERSION }}"
          git push origin "${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}