name: Create Dev Release Tag

on:
  pull_request:
    branches:
      - dev
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --match "v*.*.*-dev.*" --abbrev=0 --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "")
          if [ -z "$latest_tag" ]; then
            latest_tag="v0.0.0-dev.0"
          fi
          echo "::set-output name=tag::$latest_tag"

      - name: Parse tag
        id: parse_tag
        run: |
          IFS='.-' read -r -a parts <<< "${{ steps.get_latest_tag.outputs.tag }}"
          major=${parts[0]:1}
          minor=${parts[1]}
          dev_seq=${parts[3]}
          echo "::set-output name=major::$major"
          echo "::set-output name=minor::$((minor+1))"
          echo "::set-output name=dev_seq::$((dev_seq+1))"

      - name: Create new tag
        id: create_tag
        run: |
          new_tag="v${{ steps.parse_tag.outputs.major }}.${{ steps.parse_tag.outputs.minor }}.0-dev.${{ steps.parse_tag.outputs.dev_seq }}"
          echo "New tag: $new_tag"
          echo "::set-output name=new_tag::$new_tag"
          git tag -a "$new_tag" -m "Release $new_tag"

      - name: Push tags
        run: |
          git push --follow-tags origin HEAD:${{ github.head_ref }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
