name: Verificação de Issue Associada no PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-issue-link:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar referências de issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Instalar o GitHub CLI
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

          # Extrair números de issues mencionados no título ou corpo do PR
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}

          PR_TITLE=$(gh pr view $PR_NUMBER --repo $REPO --json title -q .title)
          PR_BODY=$(gh pr view $PR_NUMBER --repo $REPO --json body -q .body)

          ISSUE_NUMBERS=$(echo "$PR_TITLE $PR_BODY" | grep -o '#[0-9]\+' | tr -d '#')

          if [[ -z "$ISSUE_NUMBERS" ]]; then
            echo "Nenhum número de issue foi mencionado no título ou no corpo do PR."
            exit 1
          fi

          # Verificar se as issues mencionadas existem
          for ISSUE_NUMBER in $ISSUE_NUMBERS; do
            gh issue view $ISSUE_NUMBER --repo $REPO
            if [ $? -ne 0 ]; then
              echo "Issue #$ISSUE_NUMBER mencionada não existe."
              exit 1
            fi
          done
