name: Verificação de Issue Associada no PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-issue-link:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar se a pull request está associada a uma issue
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}

          # Extrair o nome do repositório
          REPO_NAME=$(echo $REPO | cut -d '/' -f 2)
          
          # Verificar se há referência à pull request em alguma issue aberta no repositório
          ISSUE_REFERENCING_PR=$(gh issue list --repo $REPO --state open --label "pull request" --search "is:open repo:$REPO_NAME$PR_NUMBER")

          if [ -z "$ISSUE_REFERENCING_PR" ]; then
            echo "Esta pull request não está associada a nenhuma issue."
            exit 1
          fi
